# Funding configuration for BenchmarkOS
# This is an academic project, but we list this for transparency

# GitHub Sponsors (if enabled in future)
# github: [haniae]

# Other funding platforms (examples - uncomment if needed)
# patreon: your-username
# open_collective: your-project
# ko_fi: your-username
# tidelift: npm/your-package

# Custom funding link
# custom: ['https://www.buymeacoffee.com/yourname', 'https://www.example.com/donate']

# Note: This is currently an academic project (GW University Practicum)
# Funding options may be added post-graduation for ongoing development

