from __future__ import annotations

import sqlite3
from pathlib import Path

from benchmarkos_chatbot.analytics_workspace import DataDictionary
from benchmarkos_chatbot.database import initialise


def test_data_dictionary_autocreates_alias(tmp_path):
    db_path = tmp_path / "workspace.db"
    initialise(Path(db_path))

    dictionary = DataDictionary(Path(db_path))
    bindings = dictionary.resolve(["Revenue"])
    binding = bindings["Revenue"]

    assert binding.canonical_metric == "revenue"
    assert binding.primary_tag is not None
    assert binding.metadata.get("autogenerated") is True

    with sqlite3.connect(db_path) as conn:
        row = conn.execute(
            "SELECT canonical_metric, primary_tag FROM metric_dictionary WHERE alias = ?",
            ("revenue",),
        ).fetchone()
    assert row is not None
    assert row[0] == "revenue"
    assert row[1] is not None


def test_data_dictionary_returns_existing_binding(tmp_path):
    db_path = tmp_path / "workspace.db"
    initialise(Path(db_path))

    dictionary = DataDictionary(Path(db_path))
    first = dictionary.resolve(["NetIncome"])
    second = dictionary.resolve(["netincome"])

    assert first["NetIncome"].canonical_metric == "net_income"
    assert second["netincome"].canonical_metric == "net_income"

